### ISSUE TITLE
Template example 

### ISSUE THREAD

**Issue by hasankhat** [QuranHub/quran-images-utils#1]
Hi, can you give me example for template_1.jpg and template_2.jpg? I didn't understand how to create template for the pages

**Comment by Abdallah-Abdelazim** [comment]
This script uses OpenCV template matching. In it, you supply a template image that's as close as you can to what you're matching in the source image. In our case here, it's really simple; We're matching the Aya number icons in the pages as we want to know where Ayas end so later we can highlight the Ayas inside the Quran image in the app. 
So you simply can crop any aya number icon from the page and use it as the template.
